server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

spring.application.name=discovery-server

logging.level.com.netflix.eureka=ERROR
logging.level.com.netflix.discovery=ERROR