server.port=0
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/microservices_db
spring.jpa.properties.hibernate.default_schema=inventory_service
spring.datasource.username=postgres
spring.datasource.password=admin

server.error.include-message=always
server.error.include-binding-errors=always

spring.application.name=inventory-service

eureka.client.prefer-same-zone-eureka=true
eureka.client.register-with-eureka=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.appname=${spring.application.name}
eureka.instance.instance-id=${spring.application.name}:${random.uuid}
#eureka.instance.preferIpAddress=true
#eureka.instance.hostname=${spring.application.name}

#spring.datasource.initialization-mode=always
#spring.datasource.initialize=true
#spring.datasource.schema=classpath:/schema.sql
#spring.datasource.continue-on-error=true
